title: Vicky Johnson-Dahl # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Cartographer 
  <br>
  and inept selfie taker 
  <br> 
  Washington DC 
  <br><br>
  <a href="https://www.twitter.com/hurricanevicky/">twitter (too frequent)</a> 
  <br>
  <a href="https://vicky.substack.com">newsletter (very infrequent)</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-P6Y7G0TC54 # your Google Analytics tracking ID here
