title: Vicky Johnson-Dahl # 
logo: "/images/logo1.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Cartographer 
  <br> 
  Washington DC 
  <br><br>
  <a href="https://www.twitter.com/hurricanevicky/">twitter</a> 
  <br>
  
  
theme: jekyll-theme-minimal
google_analytics: G-P6Y7G0TC54 # your Google Analytics tracking ID here
