title: Vicky Johnson-Dahl # 
//logo: "/images/logo1.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  cartographer
  <br> 
  washington dc 
  <br>
  <a href="https://www.twitter.com/hurricanevicky/">twitter</a> 
  <br>
  
  
theme: jekyll-theme-dinky
google_analytics: G-P6Y7G0TC54 # your Google Analytics tracking ID here
