title: 30 Day Map Challenge # 
logo: 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Vicky Johnson-Dahl
  cartographer, dc
  <br>  
  <br>
  <a href="https://www.twitter.com/hurricanevicky/">twitter</a>
  <a href="mailto:victoria.johnson@gmail.com?subject=maps!!!">email</a> 
  <br>
  
  
theme: jekyll-theme-dinky
google_analytics: G-P6Y7G0TC54 # your Google Analytics tracking ID here
